version: 0.2

phases:
  build:
    commands:
      - npm install
      - npm run test
     # - npm run sls -- deploy -s $STAGE -r $REGION
      - npm run sls -- deploy -s dev -r us-east-1
      - npm run acceptance